name: ChangeProtocol
api: [4.5.1]
version: 1.0.0
author: Estem0
main: Estem0\ChangeProtocol
mcpe-protocol: [534, 533, 532, 530, 526, 524, 516, 514, 512, 513]
description: Connect all players from 1.19 Only
